// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAsokHGbxAng_mwep38zQE-GAd_MjrQp8',
    appId: '1:532064595294:web:7bf46056bc0ed9675633cf',
    messagingSenderId: '532064595294',
    projectId: 'todah-65706',
    authDomain: 'todah-65706.firebaseapp.com',
    storageBucket: 'todah-65706.appspot.com',
    measurementId: 'G-6GSJ3DZL8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdmxYyqeKfopvau7sKW9S3bOkkoQKrehA',
    appId: '1:532064595294:android:cff0abe99b07ca7d5633cf',
    messagingSenderId: '532064595294',
    projectId: 'todah-65706',
    storageBucket: 'todah-65706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcnO31pbvP0cwq88bD4Wfuv97CegHi0uw',
    appId: '1:532064595294:ios:cf954a005503da125633cf',
    messagingSenderId: '532064595294',
    projectId: 'todah-65706',
    storageBucket: 'todah-65706.appspot.com',
    androidClientId:
        '532064595294-58b1tqaqu792r92v8lviaj0ihnn62ai9.apps.googleusercontent.com',
    iosClientId:
        '532064595294-vre86bkr3k7u31qd8m4lola7m404po42.apps.googleusercontent.com',
    iosBundleId: 'com.example.todah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcnO31pbvP0cwq88bD4Wfuv97CegHi0uw',
    appId: '1:532064595294:ios:85d4e5113d15376e5633cf',
    messagingSenderId: '532064595294',
    projectId: 'todah-65706',
    storageBucket: 'todah-65706.appspot.com',
    androidClientId:
        '532064595294-58b1tqaqu792r92v8lviaj0ihnn62ai9.apps.googleusercontent.com',
    iosClientId:
        '532064595294-vlovcs6j3gd1pc9bbct2pgenjaqcq4th.apps.googleusercontent.com',
    iosBundleId: 'com.example.todah.RunnerTests',
  );
}
